package com.fosunholiday.photo.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table photo_order_shoot
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class PhotoOrderShoot {

/**
     * 所属字段为： photo_order_shoot.user_id
     *
     * @mbg.generated
     */
private String user_id;

/**
     * 0待付款,1待拍摄,10待精修,100已完成,1000待评价,10000已取消
     * 所属字段为： photo_order_shoot.status
     *
     * @mbg.generated
     */
private Integer status;

/**
     * 用户邮箱
     * 所属字段为： photo_order_shoot.email
     *
     * @mbg.generated
     */
private String email;

/**
     * 所属字段为： photo_order_shoot.user_mobile_no
     *
     * @mbg.generated
     */
private String user_mobile_no;

/**
     * 所属字段为： photo_order_shoot.order_time
     *
     * @mbg.generated
     */
private Date order_time;

/**
     * 所属字段为： photo_order_shoot.origin_price
     *
     * @mbg.generated
     */
private BigDecimal origin_price;

/**
     * 所属字段为： photo_order_shoot.avatar_url
     *
     * @mbg.generated
     */
private String avatar_url;

/**
     * 所属字段为： photo_order_shoot.photographer_id
     *
     * @mbg.generated
     */
private String photographer_id;

/**
     * 所属字段为： photo_order_shoot.create_time
     *
     * @mbg.generated
     */
private Date create_time;

/**
     * 所属字段为： photo_order_shoot.weapp_form_id
     *
     * @mbg.generated
     */
private String weapp_form_id;

/**
     * 所属字段为： photo_order_shoot.remark
     *
     * @mbg.generated
     */
private String remark;

/**
     * 所属字段为： photo_order_shoot.order_no
     *
     * @mbg.generated
     */
private Long order_no;

/**
     * 所属字段为： photo_order_shoot.id
     *
     * @mbg.generated
     */
private String id;

/**
     * 所属字段为： photo_order_shoot.shoot_style
     *
     * @mbg.generated
     */
private String shoot_style;

/**
     * 拍摄时长
     * 所属字段为： photo_order_shoot.duration
     *
     * @mbg.generated
     */
private Byte duration;

/**
     * 所属字段为： photo_order_shoot.nick_name
     *
     * @mbg.generated
     */
private String nick_name;

/**
     * 所属字段为： photo_order_shoot.user_name
     *
     * @mbg.generated
     */
private String user_name;

/**
     * 渠道
     * 所属字段为： photo_order_shoot.order_source
     *
     * @mbg.generated
     */
private String order_source;

/**
     * 路线id
     * 所属字段为： photo_order_shoot.order_shoot_route_id
     *
     * @mbg.generated
     */
private String order_shoot_route_id;

/**
     * 约拍产品id
     * 所属字段为： photo_order_shoot.order_shoot_prod_id
     *
     * @mbg.generated
     */
private String order_shoot_prod_id;

/**
     * 所属字段为： photo_order_shoot.valid
     *
     * @mbg.generated
     */
private Boolean valid;

/**
     * 所属字段为： photo_order_shoot.update_time
     *
     * @mbg.generated
     */
private Date update_time;

/**
     * 所属字段为： photo_order_shoot.open_id
     *
     * @mbg.generated
     */
private String open_id;

/**
     * 所属字段为： photo_order_shoot.shoot_spot
     *
     * @mbg.generated
     */
private String shoot_spot;

/**
     * 所属字段为： photo_order_shoot.final_price
     *
     * @mbg.generated
     */
private BigDecimal inal_price;

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.id
     *
     * @return the value of photo_order_shoot.id
     *
     * @mbg.generated
     */
public String getId() {
    return id;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.id
     *
     * @param id the value for photo_order_shoot.id
     *
     * @mbg.generated
     */
public void setId(String id) {
    this.id = id;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.order_no
     *
     * @return the value of photo_order_shoot.order_no
     *
     * @mbg.generated
     */
public Long getOrder_no() {
    return order_no;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.order_no
     *
     * @param order_no the value for photo_order_shoot.order_no
     *
     * @mbg.generated
     */
public void setOrder_no(Long order_no) {
    this.order_no = order_no;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.order_shoot_prod_id
     *
     * @return the value of photo_order_shoot.order_shoot_prod_id
     *
     * @mbg.generated
     */
public String getOrder_shoot_prod_id() {
    return order_shoot_prod_id;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.order_shoot_prod_id
     *
     * @param order_shoot_prod_id the value for photo_order_shoot.order_shoot_prod_id
     *
     * @mbg.generated
     */
public void setOrder_shoot_prod_id(String order_shoot_prod_id) {
    this.order_shoot_prod_id = order_shoot_prod_id;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.order_shoot_route_id
     *
     * @return the value of photo_order_shoot.order_shoot_route_id
     *
     * @mbg.generated
     */
public String getOrder_shoot_route_id() {
    return order_shoot_route_id;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.order_shoot_route_id
     *
     * @param order_shoot_route_id the value for photo_order_shoot.order_shoot_route_id
     *
     * @mbg.generated
     */
public void setOrder_shoot_route_id(String order_shoot_route_id) {
    this.order_shoot_route_id = order_shoot_route_id;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.duration
     *
     * @return the value of photo_order_shoot.duration
     *
     * @mbg.generated
     */
public Byte getDuration() {
    return duration;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.duration
     *
     * @param duration the value for photo_order_shoot.duration
     *
     * @mbg.generated
     */
public void setDuration(Byte duration) {
    this.duration = duration;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.photographer_id
     *
     * @return the value of photo_order_shoot.photographer_id
     *
     * @mbg.generated
     */
public String getPhotographer_id() {
    return photographer_id;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.photographer_id
     *
     * @param photographer_id the value for photo_order_shoot.photographer_id
     *
     * @mbg.generated
     */
public void setPhotographer_id(String photographer_id) {
    this.photographer_id = photographer_id;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.order_source
     *
     * @return the value of photo_order_shoot.order_source
     *
     * @mbg.generated
     */
public String getOrder_source() {
    return order_source;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.order_source
     *
     * @param order_source the value for photo_order_shoot.order_source
     *
     * @mbg.generated
     */
public void setOrder_source(String order_source) {
    this.order_source = order_source;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.user_id
     *
     * @return the value of photo_order_shoot.user_id
     *
     * @mbg.generated
     */
public String getUser_id() {
    return user_id;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.user_id
     *
     * @param user_id the value for photo_order_shoot.user_id
     *
     * @mbg.generated
     */
public void setUser_id(String user_id) {
    this.user_id = user_id;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.open_id
     *
     * @return the value of photo_order_shoot.open_id
     *
     * @mbg.generated
     */
public String getOpen_id() {
    return open_id;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.open_id
     *
     * @param open_id the value for photo_order_shoot.open_id
     *
     * @mbg.generated
     */
public void setOpen_id(String open_id) {
    this.open_id = open_id;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.nick_name
     *
     * @return the value of photo_order_shoot.nick_name
     *
     * @mbg.generated
     */
public String getNick_name() {
    return nick_name;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.nick_name
     *
     * @param nick_name the value for photo_order_shoot.nick_name
     *
     * @mbg.generated
     */
public void setNick_name(String nick_name) {
    this.nick_name = nick_name;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.avatar_url
     *
     * @return the value of photo_order_shoot.avatar_url
     *
     * @mbg.generated
     */
public String getAvatar_url() {
    return avatar_url;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.avatar_url
     *
     * @param avatar_url the value for photo_order_shoot.avatar_url
     *
     * @mbg.generated
     */
public void setAvatar_url(String avatar_url) {
    this.avatar_url = avatar_url;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.user_name
     *
     * @return the value of photo_order_shoot.user_name
     *
     * @mbg.generated
     */
public String getUser_name() {
    return user_name;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.user_name
     *
     * @param user_name the value for photo_order_shoot.user_name
     *
     * @mbg.generated
     */
public void setUser_name(String user_name) {
    this.user_name = user_name;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.email
     *
     * @return the value of photo_order_shoot.email
     *
     * @mbg.generated
     */
public String getEmail() {
    return email;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.email
     *
     * @param email the value for photo_order_shoot.email
     *
     * @mbg.generated
     */
public void setEmail(String email) {
    this.email = email;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.shoot_spot
     *
     * @return the value of photo_order_shoot.shoot_spot
     *
     * @mbg.generated
     */
public String getShoot_spot() {
    return shoot_spot;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.shoot_spot
     *
     * @param shoot_spot the value for photo_order_shoot.shoot_spot
     *
     * @mbg.generated
     */
public void setShoot_spot(String shoot_spot) {
    this.shoot_spot = shoot_spot;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.shoot_style
     *
     * @return the value of photo_order_shoot.shoot_style
     *
     * @mbg.generated
     */
public String getShoot_style() {
    return shoot_style;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.shoot_style
     *
     * @param shoot_style the value for photo_order_shoot.shoot_style
     *
     * @mbg.generated
     */
public void setShoot_style(String shoot_style) {
    this.shoot_style = shoot_style;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.order_time
     *
     * @return the value of photo_order_shoot.order_time
     *
     * @mbg.generated
     */
public Date getOrder_time() {
    return order_time;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.order_time
     *
     * @param order_time the value for photo_order_shoot.order_time
     *
     * @mbg.generated
     */
public void setOrder_time(Date order_time) {
    this.order_time = order_time;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.user_mobile_no
     *
     * @return the value of photo_order_shoot.user_mobile_no
     *
     * @mbg.generated
     */
public String getUser_mobile_no() {
    return user_mobile_no;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.user_mobile_no
     *
     * @param user_mobile_no the value for photo_order_shoot.user_mobile_no
     *
     * @mbg.generated
     */
public void setUser_mobile_no(String user_mobile_no) {
    this.user_mobile_no = user_mobile_no;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.origin_price
     *
     * @return the value of photo_order_shoot.origin_price
     *
     * @mbg.generated
     */
public BigDecimal getOrigin_price() {
    return origin_price;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.origin_price
     *
     * @param origin_price the value for photo_order_shoot.origin_price
     *
     * @mbg.generated
     */
public void setOrigin_price(BigDecimal origin_price) {
    this.origin_price = origin_price;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.final_price
     *
     * @return the value of photo_order_shoot.final_price
     *
     * @mbg.generated
     */
public BigDecimal getInal_price() {
    return inal_price;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.final_price
     *
     * @param inal_price the value for photo_order_shoot.final_price
     *
     * @mbg.generated
     */
public void setInal_price(BigDecimal inal_price) {
    this.inal_price = inal_price;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.weapp_form_id
     *
     * @return the value of photo_order_shoot.weapp_form_id
     *
     * @mbg.generated
     */
public String getWeapp_form_id() {
    return weapp_form_id;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.weapp_form_id
     *
     * @param weapp_form_id the value for photo_order_shoot.weapp_form_id
     *
     * @mbg.generated
     */
public void setWeapp_form_id(String weapp_form_id) {
    this.weapp_form_id = weapp_form_id;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.remark
     *
     * @return the value of photo_order_shoot.remark
     *
     * @mbg.generated
     */
public String getRemark() {
    return remark;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.remark
     *
     * @param remark the value for photo_order_shoot.remark
     *
     * @mbg.generated
     */
public void setRemark(String remark) {
    this.remark = remark;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.create_time
     *
     * @return the value of photo_order_shoot.create_time
     *
     * @mbg.generated
     */
public Date getCreate_time() {
    return create_time;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.create_time
     *
     * @param create_time the value for photo_order_shoot.create_time
     *
     * @mbg.generated
     */
public void setCreate_time(Date create_time) {
    this.create_time = create_time;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.update_time
     *
     * @return the value of photo_order_shoot.update_time
     *
     * @mbg.generated
     */
public Date getUpdate_time() {
    return update_time;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.update_time
     *
     * @param update_time the value for photo_order_shoot.update_time
     *
     * @mbg.generated
     */
public void setUpdate_time(Date update_time) {
    this.update_time = update_time;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.status
     *
     * @return the value of photo_order_shoot.status
     *
     * @mbg.generated
     */
public Integer getStatus() {
    return status;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.status
     *
     * @param status the value for photo_order_shoot.status
     *
     * @mbg.generated
     */
public void setStatus(Integer status) {
    this.status = status;
}

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_order_shoot.valid
     *
     * @return the value of photo_order_shoot.valid
     *
     * @mbg.generated
     */
public Boolean getValid() {
    return valid;
}

/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_order_shoot.valid
     *
     * @param valid the value for photo_order_shoot.valid
     *
     * @mbg.generated
     */
public void setValid(Boolean valid) {
    this.valid = valid;
}


}